# Generated by Django 5.1.5 on 2025-05-19 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='Supplier',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='total_quatity',
            new_name='total_quantity',
        ),
    ]
