# Generated by Django 5.1.5 on 2025-05-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_rename_supplier_material_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialusage',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
