# Generated by Django 5.1.5 on 2025-06-10 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_materialusage_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('name', 'contact_info')},
        ),
    ]
