# Generated by Django 5.1.5 on 2025-06-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_supplier_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('name', 'type', 'supplier', 'date_added')},
        ),
    ]
