# Generated by Django 5.1.5 on 2025-07-14 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('materials', '0005_alter_material_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='material',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='materialusage',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='material',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
        migrations.AddField(
            model_name='materialtype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
        migrations.AddField(
            model_name='materialusage',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.materialtype'),
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('name', 'type', 'supplier', 'date_added', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='materialtype',
            unique_together={('name', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='materialusage',
            unique_together={('material', 'company', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('name', 'company')},
        ),
    ]
