version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  test:    
    docker:
      - image: cimg/python:3.13.1
        environment:
          DJANGO_SETTINGS_MODULE: testingGit_API.settings

    steps:
      - checkout
      
      - run:
          name: install pipenv an pip packages
          command: |
            python -m pip install --upgrade pip
            pip install -r reqiurements.txt
          # app-dir: ~/project/package-directory/  # If your requirements.txt isn't in the root directory.
          # pip-dependency-file: test-requirements.txt  # if you have a different name for your requirements file, maybe one that combines your runtime and test requirements.
      - run:
          name: Run tests
          command: |
            python manage.py test accounts.tests.test_accounts
            python manage.py test materials/tests/

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  tests:
    jobs:
      - test