version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  test_with_coverage:    
    docker:
      - image: cimg/python:3.13.1
        environment:
          DJANGO_SETTINGS_MODULE: testinggit_API.settings

    steps:
      - checkout
      
      - run:
          name: install pipenv and pip packages
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          
      - run:
          name: Run tests with coverage
          command: |
            coverage run manage.py test
            coverage report
            coverage html

      - store_artifacts:
          path: htmlcov
          destination: coverage-report

workflows:
  tests:
    jobs:
      - test_with_coverage