# Generated by Django 5.1.5 on 2025-04-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('dateOfBirth', models.DateField(max_length=20)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
