# Generated by Django 5.1.5 on 2025-05-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('foreman', 'Foreman'), ('worker', 'Worker')], default='worker', max_length=10),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
