# Generated by Django 5.1.5 on 2025-07-14 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounts_role_alter_accounts_username'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='firstName',
            field=models.CharField(default=1993, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='lastName',
            field=models.CharField(default=1993, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounts',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('foreman', 'Foreman'), ('worker', 'Worker'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('client', 'Client'), ('guest', 'Guest'), ('superUser', 'SuperUser'), ('subcontractor', 'Subcontractor')], default='worker', max_length=14),
        ),
    ]
