# Generated by Django 5.1.5 on 2025-08-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accounts_is_active_accounts_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('foreman', 'Foreman'), ('worker', 'Worker'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('client', 'Client'), ('guest', 'Guest'), ('superuser', 'SuperUser'), ('subcontractor', 'Subcontractor')], default='worker', max_length=14),
        ),
    ]
