# Generated by Django 5.1.5 on 2025-08-10 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_accounts_role'),
        ('companies', '0002_alter_company_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='company',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
            preserve_default=False,
        ),
    ]
