# Generated by Django 5.1.5 on 2025-08-10 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_accounts_company'),
        ('companies', '0002_alter_company_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
    ]
